---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoint-controller
---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-controller
  annotations:
    kubernetes.io/service-account.name: endpoint-controller
type: kubernetes.io/service-account-token
