apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-controller
  labels:
    app.kubernetes.io/name: endpoint-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: endpoint-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: endpoint-controller
    spec:
      serviceAccountName: endpoint-controller
      containers:
        - image: ghcr.io/archway-network/endpoint-controller:latest
          imagePullPolicy: Always
          name: endpoint-controller
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
              ephemeral-storage: 1Mi
            limits:
              cpu: 100m
              memory: 32Mi
              ephemeral-storage: 2Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 20000
            runAsGroup: 20000
            seccompProfile:
              type: RuntimeDefault
      
      restartPolicy: Always
