---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - clusterrole.yaml
  - serviceAccount.yaml
images:
  - name: ghcr.io/archway-network/endpoint-controller 
    newTag: 1.0.0

