---
apiVersion: v1
kind: Service
metadata:
  annotations:
    endpoint-controller-enable: "true"
    endpoint-controller-addresses: "1.1.1.1,192.168.88.12"
  name: test-service
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: test-service-rpc
    port: 26657
    protocol: TCP
    targetPort: 26657
  - name: test-service-wgrpc
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: test-service-api
    port: 1317
    protocol: TCP
    targetPort: 1317
  type: ClusterIP
