{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "endpoint-controller.serviceAccountName" . }}
  labels:
    {{- include "endpoint-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-controller
  annotations:
    kubernetes.io/service-account.name: endpoint-controller
type: kubernetes.io/service-account-token
